version: '3.8'

services:
  # Backend (ASP.NET)
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend  # Ruta al Dockerfile del backend
    ports:
      - "5000:80"  # El backend estará disponible en localhost:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db  # El backend depende de la base de datos
    networks:
      - app-network

  # Frontend (React)
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend  # Ruta al Dockerfile del frontend
    ports:
      - "3000:80"  # El frontend estará disponible en localhost:3000
    depends_on:
      - backend  # El frontend espera que el backend esté disponible
    networks:
      - app-network

  # Base de datos (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
