version: '3.8'

services:
  #Base de datos (MySQL)
  db:
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paynau
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localuser
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./Front/users-front/dockerfile  # Ruta al Dockerfile del frontend
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - app-network
      
  backend:
    build: 
      context: .
      dockerfile: ./Back/dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
